import{a as v,S as C,i as a}from"./assets/vendor-3bc7bad3.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&i(f)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const M="42920910-4418ce5fcb505a601cb14954f",S="https://pixabay.com/api/";async function g(t,e,s){try{return(await v.get(S,{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s}})).data}catch(i){throw console.error("Error fetching images:",i),i}}function y(){iziToast.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topCenter"})}const d=document.querySelector(".gallery"),L=new C(".gallery a",{captionsData:"alt",captionDelay:250});L.refresh();function E(t){t.forEach(e=>{const s=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3 class="item-title">Likes</h3> <p class="item-text">${e.likes}</p></li>
          <li class="item-description"><h3 class="item-title">Views</h3> <p class="item-text">${e.views}</p></li>
          <li class="item-description"><h3 class="item-title">Comments</h3> <p class="item-text">${e.comments}</p></li>
          <li class="item-description"><h3 class="item-title">Downloads</h3> <p class="item-text">${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;d.insertAdjacentHTML("beforeend",s)}),L.refresh()}const H=document.querySelector(".form"),p=document.querySelector(".search-input"),b=document.querySelector(".loader"),m=document.querySelector(".load-more-btn");h();let c="",n=1;const u=15;H.addEventListener("submit",q);async function q(t){if(t.preventDefault(),c=p.value.trim(),n=1,d.innerHTML="",c===""){a.error({title:"Error",message:"Please enter a search term.",position:"topCenter"}),l();return}$(),w();try{const e=await g(c,n,u),s=e.totalHits;if(e.hits.length===0){d.innerHTML="",a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),l();return}else E(e.hits),p.value="",P();u*n>=s&&(l(),y())}catch(e){console.error("Error fetching images:",e),a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{h()}}m.addEventListener("click",async()=>{try{m&&(n+=1);const t=await g(c,n,u),e=t.totalHits;E(t.hits),w(),u*n>=e&&(l(),y());const s=d.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),a.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{h()}});function w(){b.classList.remove("hidden")}function h(){b.classList.add("hidden")}function P(){m.style.display="block"}function l(){m.style.display="none"}function $(){const t=document.querySelector(".end-message");t&&t.remove()}
//# sourceMappingURL=commonHelpers.js.map
