import{a as T,S,i as l}from"./assets/vendor-3bc7bad3.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&i(f)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const C="42920910-4418ce5fcb505a601cb14954f",M="https://pixabay.com/api/";async function g(t,e,s){try{return(await T.get(M,{params:{key:C,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s}})).data}catch(i){throw console.error("Error fetching images:",i),i}}function L(){iziToast.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topCenter"})}const d=document.querySelector(".gallery"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250});E.refresh();function w(t){t.forEach(e=>{const s=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3 class="item-title">Likes</h3> <p class="item-text">${e.likes}</p></li>
          <li class="item-description"><h3 class="item-title">Views</h3> <p class="item-text">${e.views}</p></li>
          <li class="item-description"><h3 class="item-title">Comments</h3> <p class="item-text">${e.comments}</p></li>
          <li class="item-description"><h3 class="item-title">Downloads</h3> <p class="item-text">${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;d.insertAdjacentHTML("beforeend",s)}),E.refresh()}const p=document.querySelector(".scroll-to-top"),q=document.querySelector(".form"),y=document.querySelector(".search-input"),b=document.querySelector(".loader"),m=document.querySelector(".load-more-btn");h();let a="",n=1;const u=15;q.addEventListener("submit",H);async function H(t){if(t.preventDefault(),a=y.value.trim(),n=1,d.innerHTML="",a===""){l.error({title:"Error",message:"Please enter a search term.",position:"topCenter"}),c();return}P(),v();try{const e=await g(a,n,u),s=e.totalHits;if(e.hits.length===0){d.innerHTML="",l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),c();return}else w(e.hits),y.value="",x();u*n>=s&&(c(),L())}catch(e){console.error("Error fetching images:",e),l.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{h()}}m.addEventListener("click",async()=>{try{m&&(n+=1);const t=await g(a,n,u),e=t.totalHits;w(t.hits),v(),u*n>=e&&(c(),L());const s=d.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),l.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{h()}});function v(){b.classList.remove("hidden")}function h(){b.classList.add("hidden")}function x(){m.style.display="block"}function c(){m.style.display="none"}function P(){const t=document.querySelector(".end-message");t&&t.remove()}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?p.style.display="flex":p.style.display="none"});function $(){window.scrollTo({top:0,behavior:"smooth"})}p.addEventListener("click",$);
//# sourceMappingURL=commonHelpers.js.map
