import{a as L,S as w,i as a}from"./assets/vendor-b2578120.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function i(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(o){if(o.ep)return;o.ep=!0;const s=i(o);fetch(o.href,s)}})();const T="42920910-4418ce5fcb505a601cb14954f",b="https://pixabay.com/api/";async function f(r,e,i){try{return(await L.get(b,{params:{key:T,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:i}})).data}catch(l){throw console.error("Error fetching images:",l),l}}function h(){iziToast.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}const t={searchForm:document.querySelector(".form"),inputElement:document.querySelector(".search-input"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn"),galleryElement:document.querySelector(".gallery"),scrollToTopBtn:document.querySelector(".scroll-to-top")},g=new w(".gallery a",{captionsData:"alt",captionDelay:250});g.refresh();function y(r){r.forEach(e=>{const i=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img class="card-img" src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3 class="item-title">Likes</h3> <p class="item-text">${e.likes}</p></li>
          <li class="item-description"><h3 class="item-title">Views</h3> <p class="item-text">${e.views}</p></li>
          <li class="item-description"><h3 class="item-title">Comments</h3> <p class="item-text">${e.comments}</p></li>
          <li class="item-description"><h3 class="item-title">Downloads</h3> <p class="item-text">${e.downloads}</p></li>
        </ul>
        </a>
      </li>
    `;t.galleryElement.insertAdjacentHTML("beforeend",i)}),g.refresh()}function E(){return t.loader.classList.remove("hidden")}function p(){return t.loader.classList.add("hidden")}p();let c="",n=1;const m=15;t.searchForm.addEventListener("submit",v);async function v(r){if(r.preventDefault(),c=t.inputElement.value.trim(),n=1,t.galleryElement.innerHTML="",c===""){a.error({title:"Error",message:"Please enter a search term.",position:"topRight"}),d();return}B(),E();try{const e=await f(c,n,m),i=e.totalHits;if(e.hits.length===0){t.galleryElement.innerHTML="",a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d();return}else y(e.hits),t.inputElement.value="",M();m*n>=i&&(d(),h())}catch(e){console.error("Error fetching images:",e),a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{p()}}t.loadMoreBtn.addEventListener("click",async()=>{try{t.loadMoreBtn&&(n+=1);const r=await f(c,n,m),e=r.totalHits;y(r.hits),E(),m*n>=e&&(d(),h());const i=t.galleryElement.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:i*3,behavior:"smooth"})}catch(r){console.error("Error fetching more images:",r),a.error({title:"Error",message:`Error fetching more images: ${r}`})}finally{p()}});function M(){t.loadMoreBtn.style.display="block"}function d(){t.loadMoreBtn.style.display="none"}function B(){const r=document.querySelector(".end-message");r&&r.remove()}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?t.scrollToTopBtn.style.display="flex":t.scrollToTopBtn.style.display="none"});function S(){window.scrollTo({top:0,behavior:"smooth"})}t.scrollToTopBtn.addEventListener("click",S);
//# sourceMappingURL=commonHelpers.js.map
